collections:
  sections:
    output: false
  topics:
    output: true

defaults:
  - scope:
      path: "_sections/proposals"
    values:
      topic: "proposal"
  - scope:
      path: "_sections/development"
    values:
      topic: "development"